### ISSUE TITLE
Options not applied unless string

### ISSUE THREAD

**Issue by BryceBubbles** [rkingon/Craft-Plugin---Premailer#1]
Using the readme example, I noticed that some options weren't being applied. 
I've tracked it down to true/false needing to be set as strings within twig, as in 'true'/'false'.

So this works for me:
`{% premailer with { preserve_styles: 'false', remove_ids: 'true', remove_classes: 'true', remove_comments: 'true'} %}`

I see that it's been a long time since this repo saw any action, so I'm not expecting a fix, but at least the info will be here for others to find.

**Comment by rkingon** [comment]
can you PR the readme? I'll merge it in

**Comment by BryceBubbles** [comment]
I added a fix for this instead, as it's weird to have to write booleans as strings.

**Comment by rkingon** [comment]
if you PR that commit i'll merge it in

**Comment by rkingon** [comment]
I suppose I could pull in the upstream, but i'm no where near a computer right now

**Comment by rkingon** [comment]
Thanks!
