### ISSUE TITLE
Media queries removed?

### ISSUE THREAD

**Issue by maxwellhibbert** [rkingon/Craft-Plugin---Premailer#3]
I'm trying to use this with a responsive email template and the media queries are being removed. I tried adding the media query to a separate style tag with data-premailer='ignore', but that doesn't seem to work with the api. Any ideas?

**Comment by rkingon** [comment]
I know. I had to stop using it myself because of the same issue. It isn't an issue with this plugin, but an issue with Premailer API.

I want to say I created a ticket quite some time ago, but I can't remember.

Give them some hell to fix it! hah
